{% set name = "coverage-badge" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c824a106503e981c02821e7d32f008fb3984b2338aa8c3800ec9357e33345b78

build:
  number: 0
  noarch: python
  entry_points:
    - coverage-badge = coverage_badge.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - setuptools
    - coverage

test:
  imports:
    - coverage_badge
  commands:
    - coverage-badge --help

about:
  home: https://github.com/dbrgn/coverage-badge
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Generate coverage badges for Coverage.py.
  dev_url: https://github.com/dbrgn/coverage-badge

extra:
  recipe-maintainers:
    - Hoxbro
